# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manuel/ownCloud/Proenotec/Python/MonitorSerie/interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 536))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuConfiguraci_n = QtWidgets.QMenu(self.menubar)
        self.menuConfiguraci_n.setObjectName("menuConfiguraci_n")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuVer = QtWidgets.QMenu(self.menubar)
        self.menuVer.setObjectName("menuVer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_captura = QtWidgets.QAction(MainWindow)
        self.actionAbrir_captura.setObjectName("actionAbrir_captura")
        self.actionGuardar_captura = QtWidgets.QAction(MainWindow)
        self.actionGuardar_captura.setObjectName("actionGuardar_captura")
        self.actionPuertos_serie = QtWidgets.QAction(MainWindow)
        self.actionPuertos_serie.setObjectName("actionPuertos_serie")
        self.actionPuerto_serie_2 = QtWidgets.QAction(MainWindow)
        self.actionPuerto_serie_2.setObjectName("actionPuerto_serie_2")
        self.actionDecimal = QtWidgets.QAction(MainWindow)
        self.actionDecimal.setObjectName("actionDecimal")
        self.actionHexadecimal = QtWidgets.QAction(MainWindow)
        self.actionHexadecimal.setObjectName("actionHexadecimal")
        self.actionAscii = QtWidgets.QAction(MainWindow)
        self.actionAscii.setObjectName("actionAscii")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionSeleccionar_todo = QtWidgets.QAction(MainWindow)
        self.actionSeleccionar_todo.setObjectName("actionSeleccionar_todo")
        self.actionCopiar = QtWidgets.QAction(MainWindow)
        self.actionCopiar.setObjectName("actionCopiar")
        self.menuArchivo.addAction(self.actionAbrir_captura)
        self.menuArchivo.addAction(self.actionGuardar_captura)
        self.menuEditar.addAction(self.actionSeleccionar_todo)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuConfiguraci_n.addAction(self.actionPuertos_serie)
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menuVer.addAction(self.actionDecimal)
        self.menuVer.addAction(self.actionHexadecimal)
        self.menuVer.addAction(self.actionAscii)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuVer.menuAction())
        self.menubar.addAction(self.menuConfiguraci_n.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monitor serie"))
        self.pushButton_2.setText(_translate("MainWindow", "Emisora COM-A"))
        self.pushButton_3.setText(_translate("MainWindow", "Emisora COM-B"))
        self.pushButton.setText(_translate("MainWindow", "Inicio RX"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuConfiguraci_n.setTitle(_translate("MainWindow", "Configuración"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.menuVer.setTitle(_translate("MainWindow", "Ver"))
        self.actionAbrir_captura.setText(_translate("MainWindow", "Abrir captura"))
        self.actionGuardar_captura.setText(_translate("MainWindow", "Guardar captura"))
        self.actionPuertos_serie.setText(_translate("MainWindow", "Puertos serie"))
        self.actionPuerto_serie_2.setText(_translate("MainWindow", "Puerto serie B"))
        self.actionDecimal.setText(_translate("MainWindow", "Decimal"))
        self.actionHexadecimal.setText(_translate("MainWindow", "Hexadecimal"))
        self.actionAscii.setText(_translate("MainWindow", "Ascii"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))
        self.actionSeleccionar_todo.setText(_translate("MainWindow", "Seleccionar todo"))
        self.actionCopiar.setText(_translate("MainWindow", "Copiar"))
